### ISSUE TITLE
I cannot see masks

### ISSUE THREAD

**Issue by TheGrassMan1** [terranova3/hl2rp-issues#10]
**Describe the bug**
I was talking in LOOC chat with Betty Arbuckle, And she told me she had a mask, But i didn't see that

**To Reproduce**
1. Go to '.Betty Arbuckle..'
2. Click on '..nothing..'
3. Scroll down to '..nothing..'

**Expected behavior**
I wanted to see the mask but i cannot see it

**Additional context**
I don't know how to use github so i don't know what i am doing, But this bug is very annoying please help me

**Comment by adoophus** [comment]
This has been fixed.
