### ISSUE TITLE
Error accessing Settings in Helix

### ISSUE THREAD

**Issue by ValeTheEnigma** [terranova3/hl2rp-issues#11]
Server starts me out in third person, unable to toggle it as when accessing settings for helix returns Lua error loops.

**To Reproduce**
1. Go to Helix Menu
2. Click on Settings

**Expected behavior**
Expected it to open a settings menu.

**Additional context**
Happens on other servers too it seems.

[ERROR] lua/vgui/dcombobox.lua:89: bad argument #1 to 'SetText' (string expected, got nil)
  1. SetText - [C]:-1
   2. ChooseOption - lua/vgui/dcombobox.lua:89
    3. ChooseOptionID - lua/vgui/dcombobox.lua:102
     4. SetValue - gamemodes/helix/gamemode/core/derma/cl_settings.lua:429
      5. Create - gamemodes/helix/gamemode/core/derma/cl_settings.lua:735
       6. TransitionSubpanel - gamemodes/helix/gamemode/core/derma/cl_menu.lua:114
        7. OnSelected - gamemodes/helix/gamemode/core/derma/cl_menu.lua:289
         8. SetSelected - gamemodes/helix/gamemode/core/derma/cl_menubutton.lua:171
          9. unknown - gamemodes/helix/gamemode/core/derma/cl_menubutton.lua:213

**Comment by adoophus** [comment]
It seems like you have a local gmod addon that could be overriding the base HELIX user interface. I suggest going through your addons and cleaning up anything that is related to 'skins' or any sort of user interface override.
