### ISSUE TITLE
Cannot remove a langauge

### ISSUE THREAD

**Issue by Muzkito** [terranova3/hl2rp-issues#12]
**Describe the bug**
Use /charremovelanguage to remove a language. However, the command does nothing.

**To Reproduce**
1. /getlanguages to see what they have.
2. Use /charremovelanguage to remove a language that you know they have.
3. The command does nothing, doesn't remove the language nor creates an error...

**Expected behavior**
For the language to be removed.

**Comment by zacharyenriquee** [comment]
No ingame notification?

**Comment by adoophus** [comment]
Language remove was working but you weren't receiving the ingame notification for an error.

**Comment by Muzkito** [comment]
I can guarantee you it wasn't working, used /getlangauges after to check. Unless it was fixed in an update not on the server yet?
