### ISSUE TITLE
Script throwing errors when you have the required materials to craft a hammer

### ISSUE THREAD

**Issue by Zelerity** [terranova3/hl2rp-issues#14]
[ERROR] gamemodes/ixhl2rp/plugins/ixcraft/recipes/sh_recipe_tool_hammer.lua:18: attempt to call method 'GetPos' (a nil value)
  1. OnCanCraft - gamemodes/ixhl2rp/plugins/ixcraft/recipes/sh_recipe_tool_hammer.lua:18
   2. OnCanCraft - gamemodes/ixhl2rp/plugins/ixcraft/meta/sh_recipe.lua:130
    3. SetRecipe - gamemodes/ixhl2rp/plugins/ixcraft/derma/cl_crafting.lua:35
     4. LoadRecipes - gamemodes/ixhl2rp/plugins/ixcraft/derma/cl_crafting.lua:152
      5. DoClick - gamemodes/ixhl2rp/plugins/ixcraft/derma/cl_crafting.lua:113
       6. unknown - gamemodes/helix/gamemode/core/derma/cl_menubutton.lua:126

**Comment by adoophus** [comment]
Deprecated
