### ISSUE TITLE
Can't make sewn cloth.

### ISSUE THREAD

**Issue by CptPatriot** [terranova3/hl2rp-issues#17]
**Describe the bug**
When you try to make sewn cloth with all the necessary components it tells you "you do not have enough scrap cloth".

**To Reproduce**
1. Go to the crafting menu.
2. Click on Tailoring
3. Scroll down to Sewing
4. Click on sewn cloth with the necessary parts in your inventory
5. See error

**Expected behavior**
It's supposed to make sewn cloth.

**Additional context**
N/A

**Comment by adoophus** [comment]
Fixed for restart.
