### ISSUE TITLE
clothes script error

### ISSUE THREAD

**Issue by speckyaus** [terranova3/hl2rp-issues#2]
**Describe the bug**
Went to take off some clothes in my character menu, a suit. Got spammed with script errors over a dozen or so times.

**To Reproduce**
I don't know. I am no longer receiving this error when I try.

**Expected behavior**
Clothes to be slotted without error.

**Additional context**

Too many popups! Rendering will be bad! (x2)

[ERROR] gamemodes/ixhl2rp/plugins/charpane/derma/cl_charpanelitemicon.lua:110: attempt to index field 'itemTable' (a nil value)
  1. unknown - gamemodes/ixhl2rp/plugins/charpane/derma/cl_charpanelitemicon.lua:110
   2. PaintManual - [C]:-1
    3. PaintSubpanels - gamemodes/helix/gamemode/core/derma/cl_subpanel.lua:295
     4. unknown - gamemodes/helix/gamemode/core/derma/cl_menu.lua:414

**Comment by adoophus** [comment]
Fixed in 1.1.4
