### ISSUE TITLE
"You are dead" when loading a character (Likely a mysql error)

### ISSUE THREAD

**Issue by Jonesboyplays** [terranova3/hl2rp-issues#25]
I know that this has been abandoned for a LONG time, but this is the only way that someone could potentialy help  a brother out. 

The bug I'm facing is loading characters, when I try to load a character, "I am dead" and cannot do anything. I get a single error in SCRDS:
[ERROR] gamemodes/helix/gamemode/core/libs/thirdparty/sv_mysql.lua:582: [mysql] SQL Callback Error!
gamemodes/helix/gamemode/core/libs/thirdparty/sv_mysql.lua:576: [mysql] SQL Query Error!
Query: SELECT `item_id`, `inventory_id`, `panel_id`, `unique_id`, `data`, `character_id`, `player_id` FROM `ix_items`  WHERE `panel_id` = '4'
no such column: panel_id

  1. error - [C]:-1
   2. Execute - gamemodes/helix/gamemode/core/libs/thirdparty/sv_mysql.lua:582
    3. v - gamemodes/ixhl2rp/plugins/charpane/sv_database.lua:85
     4. Run - gamemodes/helix/gamemode/core/libs/sh_plugin.lua:478
      5. func - gamemodes/helix/gamemode/core/libs/sh_character.lua:898
       6. unknown - lua/includes/extensions/net.lua:33

I'm pretty new to coding, this is probably a simple mistake that I am just too dumb to comprehend. 

I expected the character to load. Thanks github.

I have a feeling that it has something to do with my characters not saving to mysql correctly. 
I had to bypass mysql (infinate loading screen, probably because I have no idea how mysql works) and use sqlite instead, which may be causing the problem. 

Thanks

**Comment by adoophus** [comment]
Seems like your tables were made before installing the schema since it's missing the panel_id on the items table

Try ix_wipedb in SRCDS console and it should generate correctly.
Backup if you need to before hand

You really shouldn't be using sqlite though, we never used it ~3 years ago so there could be a bunch of issues associated with it

**Comment by Jonesboyplays** [comment]
It was sqlite causing it. I got mysql and that fixed nearly all my problems, the rest are fixed I think. 
Thanks again!
