### ISSUE TITLE
Stream Radio

### ISSUE THREAD

**Issue by codyaus** [terranova3/hl2rp-issues#3]
https://steamcommunity.com/sharedfiles/filedetails/?id=246756300&searchtext=stream+radio

This would be awesome for EMs for Private and Public events to set the mood. I personally love to use music for my events, whether it be distant ambient music which is possible with the addon above, or loud tense music closeup.

**Comment by adoophus** [comment]
This repository is for bugs only, consider reposting using the assigned template in https://github.com/terranova3/hl2rp-suggestions
