### ISSUE TITLE
/viewdata wrong record author

### ISSUE THREAD

**Issue by Muzkito** [terranova3/hl2rp-issues#5]
**Describe the bug**
When doing /viewdata all the records are added by your unit 

**To Reproduce**
1. Do /viewdata as a unit.
2. All previous records show as being made by you.

**Expected behavior**
It should show the actual unit who submitted the record.

[https://cdn.discordapp.com/attachments/739293341828776052/748254960583442483/unknown.png](url)

**Comment by adoophus** [comment]
This has been fixed in 1.1.4
