### ISSUE TITLE
Looking at the yellow container creating errors

### ISSUE THREAD

**Issue by theHandgun** [terranova3/hl2rp-issues#6]
**Describe the bug**
When looking at the yellow container near the Commonwealth Hotel creates an error. The error breaks the description on look system. (doesn't show character descriptions i.e)

**To Reproduce**
1- Look at the yellow container.
2- You will see an error.

**Expected behavior**
There should be a description about the container instead of an error.

**Additional context**
Image of the container:
![20200827124812_1](https://user-images.githubusercontent.com/22753759/91425821-5645a580-e864-11ea-9f5f-7f4022d68222.jpg)

Error: [ERROR] gamemodes/helix/plugins/containers/entities/entities/ix_container.lua:171: attempt to index local 'definition' (a nil value)
  1. OnPopulateEntityInfo - gamemodes/helix/plugins/containers/entities/entities/ix_container.lua:171
   2. SetEntity - gamemodes/helix/gamemode/core/derma/cl_tooltip.lua:283
    3. unknown - gamemodes/ixhl2rp/plugins/aframeworkedits/cl_hooks.lua:116

Timer Failed! [ixCheckTargetEntity][@gamemodes/ixhl2rp/plugins/aframeworkedits/cl_hooks.lua (line 70)]

**Comment by adoophus** [comment]
Thanks for reporting, this has been fixed in 1.1.4
