### ISSUE TITLE
Character bug

### ISSUE THREAD

**Issue by LoraxTheXenSlayer** [terranova3/hl2rp-issues#7]
**Describe the bug**
When ever i attempt to go onto my overwatch character specifically it gives me this error: 
[ERROR] gamemodes/helix/gamemode/core/libs/sh_character.lua:1124: attempt to call method 'OnCharacterLoadFailed' (a nil value)
  1. func - gamemodes/helix/gamemode/core/libs/sh_character.lua:1124
   2. unknown - lua/includes/extensions/net.lua:32 (x2)

**To Reproduce**
1. Switch characters
2. see error

**Expected behavior**
switch my character

**Additional context**
No clue how it happened but this is a new bug. Just started happening.

**Comment by Rubberbandits** [comment]
Thanks for reporting, this has been fixed on 1.1.4.
