### ISSUE TITLE
Broken Footlockers - Racc

### ISSUE THREAD

**Issue by Racc525** [terranova3/hl2rp-issues#8]
### **FROM RACC**

**Describe the bug**
No longer able to see peoples name/description popup after looking at a CRU footlocker.

**To Reproduce**
1. Go to a CRU foot locker
2. Click on OPEN it
4. See error.

**Expected behavior**
Should operate like a normal storage unit, forcing people to reconnect to view the name and description popups.

**Additional context**
Error CODE: [ERROR] gamemodes/helix/plugins/containers/entities/entities/ix_container.lua:171: attempt to index local 'definition' (a nil value)
  1. OnPopulateEntityInfo - gamemodes/helix/plugins/containers/entities/entities/ix_container.lua:171
   2. SetEntity - gamemodes/helix/gamemode/core/derma/cl_tooltip.lua:283
    3. unknown - gamemodes/ixhl2rp/plugins/aframeworkedits/cl_hooks.lua:116

Timer Failed! [ixCheckTargetEntity][@gamemodes/ixhl2rp/plugins/aframeworkedits/cl_hooks.lua (line 70)]

**Comment by adoophus** [comment]
Hi, this has been already fixed for a future update.
Refer to: #6
