### ISSUE TITLE
Doors unown themselves and lock

### ISSUE THREAD

**Issue by Pepega1234** [terranova3/hl2rp-issues#9]
**Describe the bug**
When buying a bunch of doors in a building, sometimes when I log most of the doors become unowned and locked. I have to call an admin each time to either let me buy back the doors or unlock them

**To Reproduce**
1. Buy a bunch of doors in Rourke
2. Leave the server, wait a few hours/restart
3. Most doors you bought are unowned and locked

**Expected behavior**
Doors should still be owned by the person who bought them, even after restart. 

**Additional context**
None

**Comment by adoophus** [comment]
We'll look into this but as far as I know the 'doors not being owned after restart' thing is a deliberate thing. Unless you mean a seperate issue like a door becoming unownable after you disconnect?

**Comment by Rubberbandits** [comment]
This is intentional.
`
function PLUGIN:PlayerDisconnected(client)
	local character = client:GetCharacter()

	if (character) then
		local doors = character:GetVar("doors") or {}

		for _, v in ipairs(doors) do
			if (IsValid(v) and v:IsDoor() and v:GetDTEntity(0) == client) then
				v:RemoveDoorAccessData()
			end
		end

		character:SetVar("doors", nil)
	end
end
`

**Comment by fiercestwarrior** [comment]
@zacharyenriquee @Rubberbandits I think he's talking about the doors becoming unownable. I've noticed that most of the doors on the map are unownable for whatever reason.

Doors are really finicky anyway since the ownership can persist through characters AND if a char gets banned, they still own the door.

**Comment by Rubberbandits** [comment]
> @zacharyenriquee @Rubberbandits I think he's talking about the doors becoming unownable. I've noticed that most of the doors on the map are unownable for whatever reason.
> 
> Doors are really finicky anyway since the ownership can persist through characters AND if a char gets banned, they still own the door.

He says that the expected behavior is, "Doors should still be owned by the person who bought them, even after restart."

The reason it persists through characters is because the player switches characters but doesn't log off. I would consider that a bug.

**Comment by Pepega1234** [comment]
Why would that be deliberate. I have to ask admins to unlock the unowned
door or give me back ownership every time I join. try it yourself, buy a
bunch of doors, restart the server. Doors are broken and need to be fixed.
Just make it so when someone buys a door it stays after they leave. Also
unowned doors locked themselves and need to be opened by admins, even in
public housing areas
